[versions]
junit-jupiter = "5.12.1"
jandex = "3.3.1"
jakarta-inject = "2.0.1"
lombok = "1.18.38"
cdi-spec = "4.1.0"
validation-api = "3.1.1"
mockito = "5.14.2"
slf4j-api = "2.0.17"
common = "0.0.1-SNAPSHOT"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
jandex = { module = "org.jboss:jandex", version.ref = "jandex" }
jakarta-inject = { module = "jakarta.inject:jakarta.inject-api", version.ref = "jakarta-inject" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
cdi-spec = { module = "jakarta.enterprise:jakarta.enterprise.cdi-api", version.ref = "cdi-spec" }
validation-api = { module = "jakarta.validation:jakarta.validation-api", version.ref = "validation-api" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j-api" }
common = { module = "io.github.fungrim.blackan:common", version.ref = "common" }